const GOALS = {
  navHome: 'AKL1G0IC',
  navRSVP: 'ZYZIZ53Q',
  navRegistry: 'CTNKWGYM',
  navLocation: 'XUXFQ8KC',
  navFAQ: '5NKUOVUQ',
  navStory: 'LJG8BNRH',
  navFavorites: 'N5UUTLEU',
  navTravel: 'FU6LA5PA',
  navRSVPCTA: 'AELJNITS',
  registryNPS: '0CATGG6L',
  registryRVPottery: 'AAJ7R2U7',
  registryLMH: 'WOC1TRMO',
  favoriteCabalar: 'FZ7R0JQR',
  favoriteHorseInn: 'FOFK2RTA',
  favoriteLuca: '30H6NRI0',
  favoriteMarket: '9GEQSDLU',
  favoritePassenger: 'OZITVLYK',
  favoriteFridge: 'VQIMX6XI',
  hotelArts: 'MVOO81RT',
  hotelCork: 'HSRECAQQ',
  hotelMarriott: 'LDFRWA8V',
  RSVPAccept: 'CMFHYMOT',
  RSVPDecline: 'BOJLA3NX',
  RSVPChicken: 'ABCJIKEM',
  RSVPConfirm: 'TVJ3QQIZ',
  RSVPDinnerDetails: 'Z9SMARIJ',
  RSVPEmailWhy: 'KVB5XFH5',
  RSVPGoBack: 'GGZHFMRQ',
  RSVPHasRestrictions: '1H0IXUTY',
  RSVPNoRestrictions: 'LRTCD59H',
  RSVPSteak: 'BCGHSVBJ',
  RSVPSubmit: 'YXGQ5AYT',
  RSVPVeg: 'DV4VFH6Z',
}

export default GOALS
