name: "Chromatic"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup cache
        uses: actions/setup-node@v3.0.0
        with:
          cache: "yarn"

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: "packages/storybook"
          buildScriptName: "export"
