name: "Codecov"

on: push

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Upload app coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./apps
          fail_ci_if_error: true
          flags: app
          name: App Coverage
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload package coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./packages
          fail_ci_if_error: true
          flags: package
          name: Package Coverage
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
