name: "Codecov"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v3.0.0
        with:
          cache: "pnpm"

      - name: Install
        run: pnpm

      - name: Test
        run: pnpm test

      - name: Upload app coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./apps
          fail_ci_if_error: true
          flags: app
          name: App Coverage
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload package coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./packages
          fail_ci_if_error: true
          flags: package
          name: Package Coverage
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
