name: Pipeline
on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: yarn
        needs: checkout

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: yarn build
        needs: install

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: yarn test
        needs: build

  commitlint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: commitlint
        uses: wagoid/commitlint-github-action@v4

  codecov:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Upload app coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./apps
          fail_ci_if_error: true
          flags: app
          name: App Coverage
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload package coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./packages
          fail_ci_if_error: true
          flags: package
          name: Package Coverage
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  chromatic:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: "packages/storybook"
          buildScriptName: "export"
