name: S3 Deploy

on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - "apps/share/**"
      - ".github/workflows/s3.yml"
jobs:
  run:
    name: apps/share
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SHARE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SHARE_AWS_SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_FATHOM_TRACKING_ID: ${{ secrets.SHARE_NEXT_PUBLIC_FATHOM_TRACKING_ID }}
      NEXT_PUBLIC_FATHOM_TRACKING_DOMAINS: ${{ secrets.SHARE_NEXT_PUBLIC_FATHOM_TRACKING_DOMAINS }}
      NEXT_PUBLIC_FATHOM_TRACKING_URL: ${{ secrets.SHARE_NEXT_PUBLIC_FATHOM_TRACKING_URL }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm

      - name: Build
        run: pnpm export

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: apps/share/out
          bucket: www.tomk.link
          bucket-region: us-east-2
          dist-id: ${{ secrets.SHARE_AWS_CLOUDFRONT_ID }}
          invalidation: /
          delete-removed: false
          no-cache: true
          private: true
