name: S3 Deploy
on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - "apps/share/**"
      - ".github/workflows/s3.yml"
jobs:
  run:
    name: apps/share
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SHARE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SHARE_AWS_SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_FATHOM_TRACKING: ${{ secrets.SHARE_NEXT_PUBLIC_FATHOM_TRACKING }}
      NEXT_PUBLIC_FATHOM_SITE_DOMAINS: ${{ secrets.SHARE_NEXT_PUBLIC_FATHOM_SITE_DOMAINS }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn export

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: apps/share/out
          bucket: www.tomk.link
          bucket-region: us-east-2
          dist-id: E29ABWF8XC12PF
          invalidation: /
          delete-removed: false
          no-cache: true
          private: true
