name: "Syncpack"

on:
  # Run whenever a pull request is updated
  pull_request:
    branches:
      - main
jobs:
  syncpack:
    runs-on: ubuntu-latest
    name: syncpack
    steps:
      # Check out the branch so we can read/write its files
      - uses: actions/checkout@v3
      # Use Node.js as syncpack is written in that
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: JamieMason/syncpack-github-action@0.2.2
        with:
          package-manager: 'yarn'
        env:
          # If any options are set to 'fix' then
          # env.GITHUB_TOKEN is needed to push to PRs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
